### ISSUE TITLE
lint / coverage ?

### ISSUE THREAD

**Issue by puzrin** [jakesgordon/javascript-state-machine#101]
Hey, glad to see you back with 3.+ plans!

I did not included this changes to PRs (because those depends on your prefeneces), but probably you will find this useful:

- lint checks - must have IMHO, but coding style depends on personal preferences
- coverage reports - it worth to do it at least once, to decide what to do next.

feel free to copypaste configs if you like anything: https://github.com/nodeca/promise-memoize .

**Comment by jakesgordon** [comment]
Thanks. I'll add lint/coverage for v3.0.

**Comment by jakesgordon** [comment]
Code coverage is now performed when running the tests (and is currently at 100%) in the v3 branch (available now as a release candidate - http://codeincomplete.com/posts/javascript-state-machine-v3-0-0-rc-1/)
