### ISSUE TITLE
Suggestion for v3: semantics of config

### ISSUE THREAD

**Issue by StevenBlack** [jakesgordon/javascript-state-machine#102]
Hi Jake, I have a suggestion for v3 which would help in extending javascript-state-machine.

Currently the user passes a `cfg` parameter and this gets broken down into `var`s with `||` expressions to get defaults if `cfg.someKey` is missing.

Here's a proposal for an alternate way.

* `options` are what's provided by the user.
* `defaults` is an object of sensible default key-value pairs provided by the `StateMachine`.   Currently these are buried in the tails of `var` assignment expressions.
* `settings` is the merging of `options` on `defaults`.

    ` var settings = Object.assign( {}, defaults, options );`

And, be really slick, expose the settings.

    fsm.settings = settings;

**Comment by StevenBlack** [comment]
Another case supporting this is passing arbitrary data structures to state machines at create-time.  At the moment, everything attached to `cfg` is lost.

**Comment by StevenBlack** [comment]
(Working on this in my own fork.  It's a significant achitectural departure.  Functionally identical).

Other benefits:

* If `settings` are properly separated, then one FSM can serve a collection of settings, as opposed to individual FSM for each setting.

* The `settings` can be persisted.

**Comment by jakesgordon** [comment]
Thanks for the suggestions. v3 is making some improvements in this area.

Do you have a concrete example of what problem(s) this is solving? E.g. what exactly is it you can't do with the current behavior?

**Comment by StevenBlack** [comment]
I've outlined benefits above, most of which I'm using already.  None are possible prior.

[Here's how the create function looks now](https://github.com/StevenBlack/javascript-state-machine/blob/917eebeef75b20d86726977287aab7da26027c25/state-machine.js#L38-L108) with  `defaults -> options = settings`.

One example: processing thousands of parts per day through a half-dozen different workflows.  Each transition writes itself to the database.  In `options` I'm including part, user, access-control, and other sundry data to push parts forward or backward.

I found it odd to pass a `cfg` object that would just bin the structures I need to persist transitions.

With `defaults -> options = settings` whatever else I pass is available, in-scope, within fsm.settings.

Note that I've chosen to expose `fsm.options` and `fsm.defaults` too.  Why not?

**Comment by jakesgordon** [comment]
It sounds like the problem you are trying to solve is how to attach additional data to the FSM? (presumably so its available in the callbacks to do 'additional' work - e.g persist to DB)

Is that correct?

**Comment by StevenBlack** [comment]
I apologize, evidently I was unclear.

I don't have a problem.  This never was a "question", as this thread is presently labeled.

I'm merely proposing and [demonstrating]](https://github.com/StevenBlack/javascript-state-machine/blob/917eebeef75b20d86726977287aab7da26027c25/state-machine.js#L38-L108)  that  javascript-state-machine can improve its extensibility by opening and exposing its configuration and its eventual settings.

Turns out this is easy to do once sensible (arguably, standard) semantics for configuration are applied.

**Comment by jakesgordon** [comment]
Ok thanks, I'll keep those suggestions in mind as I rebuild for v3 (it will be a significantly different codebase)

**Comment by jakesgordon** [comment]
Some of these suggestions made it into v3. The defaults are now available (and overridable) in `StateMachine.defaults` and they are merged in with the caller options in a similar fashion (not quite as simple as Object.assign because it's not available in all browsers, but similar polyfil is used)
