### ISSUE TITLE
Uncaught TypeError: fsm.transition is not a function

### ISSUE THREAD

**Issue by madaono** [jakesgordon/javascript-state-machine#103]
hi ,i just send a ajax ,but the error happend and i dont know why. here is my code:
function getLLotteryFollowPub(i) {
    $.get(getHost()+"/active/noactive",function (data) {
        JsObj = JSON.parse(data);
        ball.ltoken[i] = JsObj.ltoken;
        fsm.transition();
    });
    return StateMachine.ASYNC;
}

thanks

**Comment by jakesgordon** [comment]
How is the function `getLLotteryFollowPub` attached to the state machine? In order to perform an ASYNC transition you should be returning `StateMachine.ASYNC` from a 'leave-state` callback.
