### ISSUE TITLE
how to restore & persist state when i reboot my server? 

### ISSUE THREAD

**Issue by luoboding** [jakesgordon/javascript-state-machine#124]
i create a StateMachine  instance, the instance persist my current state and history, when i reboot my server, the instance is released, how can i restore state?

**Comment by adami** [comment]
suggestion:

create a 'goto' transition, as explained in docs:
{name: 'goto', from: '*', to: function (s) {return s}},

save the current state (in DB, probably) after every transition.

as part of your process init process (after reboot), create the fsm and call fsm.goto(<last state>)

**Comment by tsghosh** [comment]
Hi.  can you allow file storage to store intermediate state on transition, it can survive a server restart.

**Comment by luoboding** [comment]
thank you @adami, that sounds good, i'll try your suggestion.
