### ISSUE TITLE
License  (From MIT to LGPLv3)? 

### ISSUE THREAD

**Issue by FiveHundredMiles** [jakesgordon/javascript-state-machine#126]
I believe the license for this project has changed  on Jan 7 - from MIT to LGPLv3. 
Since this is a significant change.  I hope everyone in the community using this project understands the impact to your project.

I think this should be highlighted on the project main page (or the upgrade page).

**Comment by tsghosh** [comment]
Can you comment on implications of using  this in a commercial project?

**Comment by rebulanyum** [comment]
I was wondering how the things are going to be when my contributions are merged to your repository for free and some valued customer pays you for the commercial license. Would you think if I'm required to have some payment or not? 😄

**Comment by the-simian** [comment]
@jakesgordon can this be used in a product you intend to sell currently? I see commercial licenses are no longer available?

![image](https://user-images.githubusercontent.com/954596/41828480-075ccce0-77fb-11e8-8353-516d3a2b601b.png)

It looks like yes you can sell it, but you must open source your derivative work (such as a game) and also make that game LGPLv3, is that right?

**Comment by jakesgordon** [comment]
reverted back to MIT license
