### ISSUE TITLE
[v3] QUESTION: How to pass arguments into transition calls

### ISSUE THREAD

**Issue by DavidLGoldberg** [jakesgordon/javascript-state-machine#127]
In version 2.x I used to have code working (although not released yet) like:
(excuse the Coffeescript)
`
onkey: (event, from, to, character) =>
`
or
`
onjump: (event, from, to, location) =>
    @jump location
`
I'd like to upgrade to 3.x before putting the finishing touches.  I agree with all of the upgrades to 3.x (great job).

Were people simply *not* doing this?  Is this anti state machines?  It seemed to work very well for me.  Is the answer to use the data property?  If so would I have some data register like: "currentKey/Character" and "currentLocation".  Feels less functional / declarative, but if that's the state machine way I can go with it...
Sorry if I misunderstood the docs!

If curious I'm trying to integrate this in:
https://atom.io/packages/jumpy

**Comment by adami** [comment]
I'm not sure if i understand your question.
If you're asking if you can pass your own parameters to a transition, the answer is yes - same as in V2.

if you call fsm.<transition>(x) than on the onState method you get 1st param which is lifecycle and then your parameter(s)

**Comment by DavidLGoldberg** [comment]
Ah, yes that works!  Not sure where I went wrong / got the wrong idea!

Although I think it might help to have a little more on this in the README / examples.

Anyway, thanks for the quick reply.  Very appreciated!
