### ISSUE TITLE
install question: could I install with `--save` without `--save-dev`

### ISSUE THREAD

**Issue by SilverLeaves** [jakesgordon/javascript-state-machine#166]
install question: could I install with `--save` without `--save-dev`

**Comment by RusinovAnton** [comment]
This questions is not related to the library itself. 
Please read the docs on `npm install` command:
https://docs.npmjs.com/cli/install

**Comment by SilverLeaves** [comment]
@RusinovAnton 

![default](https://user-images.githubusercontent.com/31165554/45478013-867a0380-b775-11e8-997a-3360e8757659.png)

I mean, is there any difference between the two methods for state-machine?

**Comment by SilverLeaves** [comment]
#167
