### ISSUE TITLE
Async transitions always throwing error in nodejs

### ISSUE THREAD

**Issue by munimanjunath** [jakesgordon/javascript-state-machine#169]
I wrote a simple promise in my state machine and its throwing error running on nodejs.  Is there any issue in using promises on nodejs  ?

[ 'sourcesuccess' ]
(node:82704) UnhandledPromiseRejectionWarning: [object Object]
(node:82704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:82704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:82704) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CreateOrderRequest' of undefined
    at c:\muni\finitestatemachine\routes\routes.js:934:22
    at new Promise (<anonymous>)
    at cstor.onSource (c:\muni\finitestatemachine\routes\routes.js:916:14)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:511:36)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:507:19)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:507:19)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:507:19)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:520:21)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:507:19)
    at JSM.observeEvents (c:\muni\finitestatemachine\node_modules\javascript-state-machine\lib\state-machine.js:507:19)
(node:82704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

 var FSM = StateMachine.factory({
		init: 'start',
		transitions: [
		   { name: 'startsuccess', from: 'start', to: 'Source'     },
		   { name: 'sourcesuccess', from: 'Source', to: 'Product'     },
		   { name: 'productsuccess', from: 'Product', to: 'Fetch'     },
		   { name: 'fetchsuccess', from: 'Fetch', to: 'Validatecreditcard'     }
	
		],
		data: function(inputJSON) {      //  <-- use a method that can be called for each instance
		
		  console.log(inputJSON);
		  return {
			data: inputJSON
		  }
		},
		methods: {
			
		  onStart: function(){
			  
			  console.log('state '+this.state);
	
		  },
			onSource:  function() {
						// console.log('onSource '+this.state);
					   // console.log(validateSourceTemplate);
						
					  //call validatesource request  
				  return new Promise( function (resolve, reject) {  //  <-- return a Promise instead of StateMachine.ASYNC
					var validateSourceRequest  =  Mustache.render(validateSourceTemplate, this.data);
	
					//   axios.post('http://cspwsserver:8080/CSP_ValidateSourceService/ValidateSourceService?wsdl',
					//   validateSourceRequest,
					//   { headers:
					// 	{'Content-Type' : 'text/xml',
					// 	  'SOAPAction' : 'http://www.hughes.com/validatesource/ValidateSourceService/ValidateSourceReq'
					// 	}
					
					//   }).then( response =>{
	
					// 	console.log('validatesource status '+response.status);
					// 	console.log('completed validatesource  resolving res ');
	
					// //	resolve(response );
					// //	console.log(this.data);
					// }).catch(err=>{console.log(err);  reject(err) ;});
				    if(this.data.CreateOrderRequest.AdapterNewCustomerOrderMsg!= null )	
				  	resolve('success');
					else reject('error');
				   });
	
	
	
		  },
		   onProduct : function(){
			   
						 console.log('onProduct '+this.state);
					  //  console.log(validateProductTemplate);
					//  return new Promise( function (resolve, reject) {  //  <-- return a Promise instead of StateMachine.ASYNC
	
						 var output =  Mustache.render(validateProductTemplate, this.data);
					 //   console.log('output after replacement    '+  output);
				//	 resolve('success');
	
				//	  });
	
		  },
		   onFetch  : function(){
				 //  return new Promise( function (resolve, reject) { 
					   
					//  <-- return a Promise instead of StateMachine.ASYNC
					console.log('onFetch  '+this.state);
	
			 // 	});
	
		  }, onValidatecreditcard  : function(){
						 console.log('onValidatecreditcard  '+this.state);
					//	 return new Promise( function (resolve, reject) {  //  <-- return a Promise instead of StateMachine.ASYNC
							console.log('onFetch  '+this.state);
							this.data.Code = "1000" ;
							this.data.Message = "Successful Response" ;
				//			resolve('success');
				//		  });
					  
					  this.data.Code = "1000" ;
					  this.data.Message = "Successful Response" ;
				   //  console.log('I am ' + JSON.stringify(this.data));
	
		  },
		  describe: function() {
			console.log('I am ' + JSON.stringify(this.data));
		  }
		}
	  });

**Comment by jgrocha** [comment]
@munimanjunath As far I can see in your report, _only a warning is reported_. It is not an error.

It is the default node behaviour, to report that warning on the console. You can check [node documentation](https://nodejs.org/api/process.html#process_event_rejectionhandled) or you can google it. There are many blogs about this issue, like [Unhandled Promise Rejections in Node.js](https://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html).

To prevent this warning on the console, you can add `.catch()` on the promise with an empty function, like this:

```javascript
    onBeforePreparation: function (lifecycle) {
      return new Promise((resolve, reject) => {
        setTimeout(() => reject('uh oh'), 2000);
      }).catch(() => {});
    },
```
