### ISSUE TITLE
v3.0+ has no type definition file for typescript.

### ISSUE THREAD

**Issue by dziesig** [jakesgordon/javascript-state-machine#187]
I am trying to use the javascript-state-machine V3.01 from a react/typescript app.  Unfortunately, it will not compile due to incompatibility between the V3 code and the V2.4 index.d.ts file.  I will attempt to produce a V3 index.d.ts file, but if I do, it will be my first ;).  Hopefully someone more experienced in typescript has already done this but forgot to commit it.

Thanks,
Don

**Comment by beltschatsar** [comment]
Someone already done this. Will post more info when I got time

**Comment by beltschatsar** [comment]
https://github.com/jakesgordon/javascript-state-machine/pull/134 Here it is

**Comment by dziesig** [comment]
Thanks
