### ISSUE TITLE
Observers for state changes

### ISSUE THREAD

**Issue by Rodeoclash** [jakesgordon/javascript-state-machine#26]
I'm not sure how this fits in with the state machine programming paradigm but external observers attached to states on the state machine I think would be a really good feature.

sm = new StateMachine() ...

observer = sm.observe('stateName', function() { alert('in the state'); });

sm.doStateChange() would fire the observer.

observer would contain a UID which could be used to unbind the observer again:

sm.removeObserver(observer);

Thoughts? Would this be a good fit for the project or is it straying from the core functionality too far? Maybe I'm missing something with what's there already :)

**Comment by jakesgordon** [comment]
Lifecycle events are now observable in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/lifecycle-events.md#observing-lifecycle-events
