### ISSUE TITLE
Conditional branching logic for transitions

### ISSUE THREAD

**Issue by garjitech** [jakesgordon/javascript-state-machine#27]
Depending on the system, it might be desirable to have conditional branching logic for the transitions.  I've implemented this feature via an optional function parameter for each event definition.  If you are interested let me know and I'll clean it up a bit and send the pull request.

**Comment by jakesgordon** [comment]
Conditional transitions (using a function for `to`) is now supported in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/states-and-transitions.md#conditional-transitions
