### ISSUE TITLE
DOT (graphviz) export

### ISSUE THREAD

**Issue by eagsalazar** [jakesgordon/javascript-state-machine#31]
I saw you mentioned this as a future feature but I'm bringing it up again so it is listed as a feature request in issues and you know people are interested.

Thanks for this great little project.

**Comment by ArnaudValensi** [comment]
I rebased it: https://github.com/ArnaudValensi/javascript-state-machine

**Comment by potherca** [comment]
:+1:

**Comment by jakesgordon** [comment]
Graphviz export is now supported in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/visualization.md

**Comment by Sneko** [comment]
@jakesgordon do you know an existing way to "parse/import" a dot file to be used by this javascript-state-machine library?

Thanks!
