### ISSUE TITLE
Improve ASYNC behavior with a transition.pause/continue/cancel model

### ISSUE THREAD

**Issue by smeijer** [jakesgordon/javascript-state-machine#42]
It's possible to pause the statemachine by returning StateMachine.ASYNC from the onleave event. The point I'm trying to make, is that method 1 shouldn't know anything about method 2. 

So, if method 2 is running some async code and the statemachine has to wait while it's running, than method 2 should be responsible for pausing the statemachine instead of (an event of) method 1

Idea's to solve the problem:
- Make it possible to return StateMachine.ASYNC from the onbefore event.
- Add a function that does the opposite of fsm.transition().

The first can be used like:

```
callbacks: {
     onbeforeFetch: function(event, from, to) {
         return StateMachine.ASYNC;
     },
     onFetch: function(event, from, to) {
         $.getJSON(url, function(data) {
             this.transition();
         });   
     }
 }
```

and the second like: (my personal favorite)

```
callbacks: {
     onFetch: function(event, from, to) {
         this.transition.await()
         $.getJSON(url, function(data) {
             this.transition();
         }).error(function() { 
             this.transition.cancel();
         });   
     }
 }
```

**Comment by jakesgordon** [comment]
I will be switching the ASYNC behavior to use Promises in v3.

**Comment by jakesgordon** [comment]
All lifecycle events can now be 'paused' by returning a Promise in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/async-transitions.md

**Comment by smeijer** [comment]
Awesome. Nice work.
