### ISSUE TITLE
THOUGHTS FOR VERSION 3.0

### ISSUE THREAD

**Issue by jakesgordon** [jakesgordon/javascript-state-machine#48]
I have some (preliminary) plans on building a new 3.0 version, almost certainly NOT backward compatible, but including some of the common requests for:
- nested/composable states
- conditional transitions
- observers (pub/sub) for state changes (instead of singular on**\* callbacks)
- stacked states (undo/redo)

**Comment by babnik63** [comment]
Hi guys, this is a long time with no update, is this project going forward?
we can enrich this library by connecting to a database and I have some ideas.

**Comment by victorwoo** [comment]
Yes, I think camel-casing is important. It make code normal and like others.

**Comment by wallslide** [comment]
Sometimes the decision on whether the state machine should really be changing states or not is dependent on an asynchronous call. An important feature for me would be support for returning true/false asynchronously in the `onbefore` hooks.

**Comment by DmitryMyadzelets** [comment]
Asynchronous transition functionality makes automata *not deterministic*. If a transition requires time, it is actually not a transition, it is a state which have entering, exit and canceling events. Please, remove asynchronous transitions in the v3.0.

For an external observer, an automaton should *always* have a current state. Otherwise: "What's your state? I have no idea, I'm making a transition, please wait, wait, wait...".

**Comment by Rodeoclash** [comment]
No comments, I just wanted to weigh in and say this is a library that I've used over many years and is my go to whenever I need any sort of state machine in JavaScript. It's awesome and I look forward to V3. Thanks!

**Comment by peacedove** [comment]
Make some small change to make the callback function camel-casing

https://github.com/peacedove/javascript-state-machine/commit/72fbe82919dad39398f9b6f281654e3c758c9687

**Comment by mushtat** [comment]
Since fsm currently can run in node environment - it would be good if there is npm package. Can you please add it in next version?

**Comment by hunterino** [comment]
I would like a transition function.
example:

fsm.transition('warn');

That way, the code doesn't need to know anything about the state machine it's working with.

**Comment by davestewart** [comment]
Hello everyone,

Jake has very kindly let me post in his issues thread about my new project release, a new JavaScript state machine that is fully object-oriented, event driven and incredibly easy to configure:

- https://github.com/davestewart/javascript-state-machine

It comes with a ton of awesome demos, and save for the HFSM (planned for version 1.1) covers off probably most of the main requests for Jakes FSM.

Please do check it out and spread the word if you like it.

Thanks for reading, and thanks Jake for letting me post!

**Comment by jakesgordon** [comment]
v3 is now available (with many of these suggestions) as a release candidate - http://codeincomplete.com/posts/javascript-state-machine-v3-0-0-rc-1/
