### ISSUE TITLE
TypeError: Object #<object> has no method 'apply'

### ISSUE THREAD

**Issue by drmikecrowe** [jakesgordon/javascript-state-machine#63]
Any thoughts on debugging TypeError: Object #<object> has no method 'apply'?

I'm building the FSM inside a class as follows: 

```
this.fsm = StateMachine.create({
    initial: constants.S_CSM_COLD,
    events: [
        { from: constants.S_CSM_COLD,        name: constants.E_SCK_GUI_STARTUP,             to: constants.S_CSM_REGISTER},
        { from: constants.S_CSM_REGISTER,    name: constants.E_CSM_REGISTER_SUCCESS,        to: constants.S_CSM_WAITING},
        ....
    ],
    callbacks: {
        onS_CSM_REGISTER:       this.register,
        ...
    }
});
```

Inside a callback from a socket.io connect, I call: 

```
self.fsm.E_SCK_GUI_STARTUP();
```

and it transitions into my register state.

However, from within my register state, I'm trying to fire the next transition by calling: 

```
self.fsm.E_CSM_REGISTER_SUCCESS();
```

However, it is generating the TypeError: Object #<object> has no method 'apply' error.

Not sure how the first transitions fine, but the second doesn't.

Any help greatly appreciated.

**Comment by thesebas** [comment]
I don't know your `constants` definition but just to be sure you should call it like:

    self.fsm[constants.E_SCK_GUI_STARTUP]();
    self.fsm[constants.E_CSM_REGISTER_SUCCESS]();

cuz maybe `constants` definition has some errors like:

    var constants = {
      E_SCK_GUI_STARTUP: "E_SCK_GUI_STARTUP",
      E_CSM_REGISTER_SUCCESS: "some_nasty_typo_E_CSM_REGISTER_SUCCESS"
    };

and then `fsm.some_nasty_typo_E_CSM_REGISTER_SUCCESS()` instead of `fsm.E_CSM_REGISTER_SUCCESS()` is valid.

**Comment by jakesgordon** [comment]
You probably need to bind the callback to ensure its scoped to your main object (as opposed to the fsm itself)

    callbacks: {
      onS_CSM_REGISTER: this.register.bind(this)
    }
