### ISSUE TITLE
perhaps generic events should come before and after specific events

### ISSUE THREAD

**Issue by bughit** [jakesgordon/javascript-state-machine#68]
they are good for logging and debugging and so bracketing specific events would be useful
- onbeforeevent - generic handler for all events
  - onbeforego - specific handler for the go event only
    - onleavestate - generic handler for all states
      - onleavered - specific handler for the red state only
      - onentergreen - specific handler for the green state only
    - onenterstate - generic handler for all states
  - onaftergo - specific handler for the go event only
- onafterevent - generic handler for all events

**Comment by jakesgordon** [comment]
Yup, this is the new behavior in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/lifecycle-events.md
