### ISSUE TITLE
Missing `transitions` method?

### ISSUE THREAD

**Issue by tkambler** [jakesgordon/javascript-state-machine#73]
According to the documentation, a new instance should have the following member:

> fsm.transitions() - return list of events that are allowed from the current state

This doesn't appear to be implemented?

**Comment by jakesgordon** [comment]
That method was added just this past weekend - are you running the latest master branch?

**Comment by tkambler** [comment]
2.3.2 as installed via `npm`

**Comment by jakesgordon** [comment]
The latest version (2.3.4), which includes this feature has now been pushed to npm

FYI: however there is a bug in the feature which I need to fix (see issue #74)
