### ISSUE TITLE
Callback not be called when transition to same state

### ISSUE THREAD

**Issue by valaxy** [jakesgordon/javascript-state-machine#77]
I meet the problem that described here https://github.com/jakesgordon/javascript-state-machine/issues/14
I think the bug it's not completely repaired, please see the code below, it demonstrate what I mean.

``` javascript```
var count = 0
var fsm = StateMachine.create({
    initial: 'hide',
    events: [
        {name: 'open', from: 'hide', to: 'show'},
        {name: 'again', from: 'show', to: 'show'},
        {name: 'close', from: 'show', to: 'hide'}
    ],
    callbacks: {
        onentershow: function () {
            count++
        }
    }
})
fsm.open()   // expect count++
fsm.again()  // expect count++
fsm.again()  // expect count++
fsm.close()
assert.equal(count, 3) // error as count == 1
```

**Comment by valaxy** [comment]
OK, I check the code which shows:
```
if (from === to) {
    StateMachine.afterEvent(this, name, from, to, args);
    return StateMachine.Result.NOTRANSITION;
}
```
Maybe I should use onafterevent instead of onenterstate

**Comment by peacechen** [comment]
Thanks for noting this, saved me some time :)

I also vote for calling the onenterSTATE handler when a state transitions to itself.  Users who don't want to handle that case could just compare the "from" and "to" parameters.  Or could make this behavior optionally activated through a create() parameter.

**Comment by mrcybermac** [comment]
I agree with the sentiment here:  we should have the choice to have state handlers called either once per state change or every time a state is entered (even if repeated like "red" to "red" to "red").  I suggest that the library allow for an optional config per state which defaults to the original behavior but offers a choice of something like 'trigger: always'

states: {
     red:  {
          trigger: always
     }
}

... then, just for the 'red' state, all state handlers would be called every time 'red' is entered, even if from 'red', while all other states would default to the original behavior.

**Comment by reeshkov** [comment]
I also need the behavior

**Comment by mikkelking** [comment]
Mike Daly @seeq12 has pushed a change which does this I think... better have a look

**Comment by jakesgordon** [comment]
This behavior can now be opted into with v3 by specifying `observeUnchangedState: true` in your state machine config.

(NOTE: it didn't make into v3.0.0-rc.1, but will be available in the next release candidate and the official v3 release)
