### ISSUE TITLE
may be nonesence？

### ISSUE THREAD

**Issue by chuandadexiaoyu** [jakesgordon/javascript-state-machine#79]
state-machine.js    69 and 74   line, are the two judements nonesence? 

```
  for(var name in map) {
    if (map.hasOwnProperty(name)) //  is this judement nonesence?
      fsm[name] = StateMachine.buildEvent(name, map[name]);
  }   

  for(var name in callbacks) {
    if (callbacks.hasOwnProperty(name)) // is this judement nonesence?
      fsm[name] = callbacks[name]
  }
```

**Comment by peacechen** [comment]
hasOwnProperty() is commonly used while enumerating to prevent iterating over inherited types.  This prevents inherited prototype objects such as the default toString() from being enumerated.

http://stackoverflow.com/questions/9396569/javascript-what-is-property-in-hasownproperty

**Comment by jakesgordon** [comment]
Yup, that is correct. Thanks.
