### ISSUE TITLE
behavior when transition() is called before StateMachine.leaveAnyState()

### ISSUE THREAD

**Issue by MisterFreeze** [jakesgordon/javascript-state-machine#80]
I defined a `onleaveSTATE` function that returns `StateMachine.ASYNC`. The asynchronous part _maybe_ does a long running task. If it does not, it calls `transition` immedeately. This results in `onenterstate` to run before `onleavestate`, which is not the behavior I would expect.

**Comment by jakesgordon** [comment]
The fix for this is going to require changing the ASYNC code to use a Promise based system (which is planned for upcoming v3)

**Comment by jakesgordon** [comment]
Async behavior has been changed to use a less error prone Promise based system in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/async-transitions.md
