### ISSUE TITLE
ASYNC leaveThisState and leaveAnyState

### ISSUE THREAD

**Issue by MisterFreeze** [jakesgordon/javascript-state-machine#81]
Both function I mentioned in the subject may execute asynchronously and end their asynchronous action by calling `transition`. `transition` continues the state transition and executes further functions to end the event. There are two consequences of this behavior:
- either `leaveThisState` or `leaveAnyState` may still be running when entering a new state
- the transition cannot be `cancel()`d after one of the two called `transition`

It could be helpful to give a hint on this behavior or to not allow both functions to run asynchronously. A solution I would find more interesting was to execute `transition` depending on the return values of `leaveThisState` and `leaveAnyState`.

**Comment by Sendami** [comment]
:+1:

**Comment by jakesgordon** [comment]
Yes, this is a bug, I shouldn't call BOTH versions of leave if one of them returns an ASYNC.

**Comment by jakesgordon** [comment]
The async behavior has been rewritten to use a less error-prone Promise based system in v3 - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/async-transitions.md
