### ISSUE TITLE
return StateMachine.ASYNC only on leaveState?

### ISSUE THREAD

**Issue by michi3** [jakesgordon/javascript-state-machine#82]
Hi Dev,

i'm using your lib and I'm a fan of it. But now i discovered something which is a huge problem for me.

Why is return StateMachine.ASYNC; only working from the leaveState callback?

i have a fromStates which can be transitioned to various toStates.
I want to do AJAX-Calls during state transitions.

So if i return StateMachine.ASYNC; on the leavestate callback, the event is not executed because the machine is halted and the AJAX-Call never gets fired and the AJAX-Callback can not call .transition();

I cannot call the AJAX-Call in the onleavestate because i don't know which call (the event defines this). So i ended up with a switch statement on the leavestate callbacks and check the "to" variable and call the appropriate AJAX-Call and then halt the maschine. This sucks :( I started using the maschine because i don't wonna see this switch statements anymore. Every case has its own event.

So can someone help me? Am I using this lib wrong?
Is there a reason why return StateMachine.ASYNC; only works onleavestate?
Is there a easy way to change this behavior?

thx!!!

**Comment by zazabe** [comment]
:+1:

**Comment by mogadanez** [comment]
my 5 cents:

Use it same, transition between states  executes ajax request

if even i put switch in onleave,  it's hard to deal with  ajax errors. 
I should define extra event and route back to return machine to previous state

**Comment by jakesgordon** [comment]
In next version (v3) the ASYNC behavior will be switched to Promises (e.g. if you return a promise the FSM wont transition until you fulfill the promise), and will likely be supported in for both leave and enter callbacks.

**Comment by jakesgordon** [comment]
Async behavior is now based on Promises and is available for any of the lifecycle events - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/async-transitions.md
