### ISSUE TITLE
Not able to reset the state machine

### ISSUE THREAD

**Issue by Sendami** [jakesgordon/javascript-state-machine#86]
Hey guys, 
Is there any way we can stop or reset the state machine, and then start from the initial state?

Thanks in advance, 
Senda

**Comment by Wasini** [comment]
try seting fsm.current = 'initialstate'
not sure how that will work

**Comment by SimoneTaliercio** [comment]
+1 for this feature request : )

**Comment by mikkelking** [comment]
@robhicks added a method transitionTo, and I have merged that into a fork along with some other changes from other contributors. I am currently testing these, and will submit a pull request once happy with it. You can clone my fork if you like.

**Comment by jakesgordon** [comment]
In v3 - You can easily define a wildcard 'reset' transition to get back to an initial state - https://github.com/jakesgordon/javascript-state-machine/blob/v3/docs/states-and-transitions.md#wildcard-transitions
