### ISSUE TITLE
Multiple 'from' and 'to' states for a single event gives error in node cmd with jasmine.

### ISSUE THREAD

**Issue by NimishChandola** [jakesgordon/javascript-state-machine#88]
Initializing the state machine like below works properly in browser but not in node console when writing jasmine unit test cases.
var fsm = StateMachine.create({
  initial: 'hungry',
  events: [
    { name: 'rest', from: ['hungry', 'satisfied', 'full', 'sick'], to: 'hungry'    },
]});

When i am creating a jasmine unit test and run it in node console then it throws error because
in console it generate "map" json object like {"hungry,satisfied,'full','sick'" : "hungry"}
and map[event].hasOwnProperty(this.current) is failing at line 79

If we check it in browser "map" object will be like
{'hungry':'hungry', 'satisfied':'hungry', 'full':'sick', 'sick':'hungry'} which is correct.

**Comment by Arunkumar-MS** [comment]
@jakesgordon Even i am also facing same problem while writing an unit for it using jasmine :(

**Comment by rakesh-nayak** [comment]
@NimishChandola 

I also faced the same problem.

Then I changed the code as below

var fsm = StateMachine.create({
initial: 'hungry',
events: [
    {name: 'rest', from: 'hungry', to: 'hungry' },
    {name: 'rest', from: 'satisfied', to: 'hungry' },
    {name: 'rest', from: 'full', to: 'hungry' },
    {name: 'rest', from: 'sick', to: 'hungry' }
]});

And unit test started working. But I am not sure is this a good idea to do that or not.

@jakesgordon : I believe for writing the unit test case we should not modify the actual implementation .. but I could not find any other way. Is this correct way to do this?

**Comment by NimishChandola** [comment]
I debug code and get to know  that when we use injectr module for unit testing then "instance of Array" is not returning true though there is an array and due to that for multiple 'to' ,  array generate like
 [ ['hungry', 'satisfied', 'full', 'sick']] 
check the below code at line 49
 var from = (e.from instanceof Array) ? e.from : (e.from ? [e.from] : [StateMachine.WILDCARD]);

**Comment by NimishChandola** [comment]
The issue is coming due to injector module, but as part of defensive programming i have updated the condition so that due to some other library issue , our code should not break.

**Comment by jakesgordon** [comment]
This is fixed in (upcoming) v3
