### ISSUE TITLE
transitions() doesn't return events that use a wildcard in the "from" property

### ISSUE THREAD

**Issue by Shaunm44** [jakesgordon/javascript-state-machine#93]
Been messing with the FSM (thanks btw, tons of headache avoided b/c of this) and tried using the wildcard feature. Unfortunately, when I call "transitions()" is doesn't return those events with it.

But, I have a fix in mind that I'm using to hold me over.

I simply changed the definition of the transitions function by combining the transitions of the current node with that of the wildcard.

`fsm.transitions = function()      { return transitions[this.current].concat(transitions[StateMachine.WILDCARD]); };`

It works for now, but I will continue to test and update if I notice any glaring issues with this.

**Comment by jakesgordon** [comment]
Fixed - PR merged (and unit tests fixed/added) for the (upcoming) v2.4 release.

Thanks!
