### ISSUE TITLE
Returning a value(Promise?) from ASYNC event handlers

### ISSUE THREAD

**Issue by yarandoo** [jakesgordon/javascript-state-machine#94]
Hi, 

If I understood correctly every event handler that is async needs to return StateMachine.ASYNC and then call fsm.transition().

In my use case I would like the event handler to be async but to also compute some value and to be returned (this value will be used by the caller). As I am forced to return ASYNC, I am not able to return any value from my custom event handler. Is there any easy way to support my use case?

Are promises going to be supported in the future?

Thanks!

**Comment by jakesgordon** [comment]
Yes, version 3 will replace the current ASYNC behavior with Promises (the E.T.A for v3 is end of 2016)
