### ISSUE TITLE
How do you pass values between two states?

### ISSUE THREAD

**Issue by hcoderonly** [jakesgordon/javascript-state-machine#96]
I was wondering how would you pass values between two states?
For Example:
I am in State A, and I am going to State B
I want a json object to be passed from State A to State B?
Can I achieve it with this library? and how?

**Comment by jakesgordon** [comment]
Any arguments you pass when calling an event method will be passed thru to all callbacks as the last argument(s)

    var fsm = StateMachine.create({
        initial: 'A',
        events: [
            { name: 'go', from: 'A', to: 'B' }
        ],
        callbacks: {
          onB: function(event, from, to, data) { alert('entered state B: ' + data.msg); }
        }
    });

    fsm.go({ msg: "this is a custom message" });

Does that help?
